export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";

type ParameterMetadata = {
  label: string;
  type: "text" | "number" | "select";
  options?: string[];
  placeholder?: string;
};

export interface EndpointConfig {
  method: HttpMethod;
  path: string;
  name: string;
  description?: string;
  hasCommonParams: boolean;
  specificParams?: string[];
  requiredParams?: string[];
  pathParams?: string[];
  hasRequestBody?: boolean;
  requestBodyExample?: object;
  parameterMetadata?: Record<string, ParameterMetadata>;
}

export interface EndpointCategory {
  name: string;
  endpoints: EndpointConfig[];
}

export const endpointCategories: EndpointCategory[] = [
  {
    name: "Strony",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site",
        name: "Pobierz stronę",
        description: "Zwraca szczegóły wybranej strony",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/has-data",
        name: "Sprawdź dane strony",
        description: "Zwraca informację, czy strona otrzymała zdarzenia analityczne",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/is-public",
        name: "Sprawdź publiczny status strony",
        description: "Zwraca informację, czy strona jest publicznie dostępna",
        hasCommonParams: false,
      },
      {
        method: "DELETE",
        path: "/sites/:site",
        name: "Usuń stronę",
        description: "Trwale usuwa stronę i wszystkie jej dane. Wymaga roli administratora lub właściciela.",
        hasCommonParams: false,
      },
      {
        method: "PUT",
        path: "/sites/:site/config",
        name: "Aktualizuj konfigurację strony",
        description: "Aktualizuje konfigurację strony. Wymaga roli administratora lub właściciela.",
        hasCommonParams: false,
        hasRequestBody: true,
        requestBodyExample: {
          public: true,
          blockBots: true,
          excludedCountries: ["CN", "RU"],
        },
      },
      {
        method: "GET",
        path: "/sites/:site/excluded-ips",
        name: "Pobierz wykluczone adresy IP",
        description: "Zwraca listę wykluczonych adresów IP",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/excluded-countries",
        name: "Pobierz wykluczone kraje",
        description: "Zwraca listę wykluczonych kodów krajów",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/excluded-paths",
        name: "Pobierz wykluczone ścieżki",
        description: "Zwraca listę wykluczonych ścieżek URL",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/excluded-hostnames",
        name: "Pobierz wykluczone hosty",
        description: "Zwraca listę wykluczonych hostów",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/excluded-user-agents",
        name: "Pobierz wykluczone user-agenty",
        description: "Zwraca listę wykluczonych wzorców user-agent",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/private-link-config",
        name: "Pobierz konfigurację prywatnego linku",
        description: "Zwraca konfigurację klucza prywatnego linku",
        hasCommonParams: false,
      },
      {
        method: "POST",
        path: "/sites/:site/private-link-config",
        name: "Aktualizuj prywatny link",
        description: "Generuje lub unieważnia klucz prywatnego linku. Wymaga roli administratora lub właściciela.",
        hasCommonParams: false,
        hasRequestBody: true,
        requestBodyExample: {
          action: "generate_private_link_key",
        },
      },
    ],
  },
  {
    name: "Organizacje",
    endpoints: [
      {
        method: "GET",
        path: "/organizations",
        name: "Pobierz moje organizacje",
        description:
          "Zwraca wszystkie organizacje, których członkiem jest zalogowany użytkownik, wraz z członkami każdej organizacji",
        hasCommonParams: false,
      },
      {
        method: "POST",
        path: "/organizations/:organizationId/sites",
        name: "Utwórz stronę",
        description: "Tworzy nową stronę w organizacji. Wymaga roli administratora lub właściciela.",
        hasCommonParams: false,
        pathParams: ["organizationId"],
        hasRequestBody: true,
        requestBodyExample: {
          domain: "example.com",
          name: "Moja strona",
          public: false,
          blockBots: true,
          saltUserIds: false,
          excludedIPs: [],
          excludedCountries: [],
          sessionReplay: false,
          webVitals: false,
          trackErrors: false,
          trackOutbound: true,
          trackUrlParams: true,
          trackInitialPageView: true,
          trackSpaNavigation: true,
          trackIp: false,
          trackButtonClicks: false,
          trackCopy: false,
          trackFormInteractions: false,
          tags: [],
        },
      },
      {
        method: "GET",
        path: "/organizations/:organizationId/sites",
        name: "Pobierz strony organizacji",
        description: "Zwraca wszystkie strony w organizacji widoczne dla zalogowanego użytkownika",
        hasCommonParams: false,
        pathParams: ["organizationId"],
      },
      {
        method: "GET",
        path: "/organizations/:organizationId/members",
        name: "Pobierz członków organizacji",
        description: "Zwraca wszystkich członków organizacji wraz ze szczegółami użytkowników",
        hasCommonParams: false,
        pathParams: ["organizationId"],
      },
      {
        method: "POST",
        path: "/organizations/:organizationId/members",
        name: "Dodaj członka organizacji",
        description: "Dodaje użytkownika do organizacji z określoną rolą",
        hasCommonParams: false,
        pathParams: ["organizationId"],
        hasRequestBody: true,
        requestBodyExample: {
          email: "user@example.com",
          role: "member",
        },
      },
    ],
  },
  {
    name: "Zespoły",
    endpoints: [
      {
        method: "GET",
        path: "/organizations/:organizationId/teams",
        name: "Pobierz zespoły",
        description: "Zwraca zespoły w organizacji wraz z członkami i stronami",
        hasCommonParams: false,
        pathParams: ["organizationId"],
      },
      {
        method: "POST",
        path: "/organizations/:organizationId/teams",
        name: "Utwórz zespół",
        description: "Tworzy zespół. Wymaga roli administratora lub właściciela.",
        hasCommonParams: false,
        pathParams: ["organizationId"],
        hasRequestBody: true,
        requestBodyExample: {
          name: "Marketing",
          memberUserIds: [],
          siteIds: [],
        },
      },
      {
        method: "PUT",
        path: "/organizations/:organizationId/teams/:teamId",
        name: "Aktualizuj zespół",
        description: "Aktualizuje nazwę zespołu, członków lub strony. Wymaga roli administratora lub właściciela.",
        hasCommonParams: false,
        pathParams: ["organizationId", "teamId"],
        hasRequestBody: true,
        requestBodyExample: {
          name: "Rozwój",
        },
      },
      {
        method: "DELETE",
        path: "/organizations/:organizationId/teams/:teamId",
        name: "Usuń zespół",
        description: "Usuwa zespół. Wymaga roli administratora lub właściciela.",
        hasCommonParams: false,
        pathParams: ["organizationId", "teamId"],
      },
    ],
  },
  {
    name: "Przegląd",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/overview",
        name: "Pobierz przegląd",
        description: "Zwraca główne metryki analityczne strony",
        hasCommonParams: true,
      },
      {
        method: "GET",
        path: "/sites/:site/overview/time-series",
        name: "Pobierz przegląd w czasie",
        description: "Zwraca dane analityczne w szeregu czasowym podzielone na przedziały czasu",
        hasCommonParams: true,
        specificParams: ["bucket"],
      },
      {
        method: "GET",
        path: "/sites/:site/metric",
        name: "Pobierz metrykę",
        description: "Zwraca analitykę wymiarową podzieloną według wybranego parametru",
        hasCommonParams: true,
        specificParams: ["parameter", "limit", "page"],
        requiredParams: ["parameter"],
      },
      {
        method: "GET",
        path: "/sites/:site/page-titles",
        name: "Pobierz tytuły stron",
        description: "Zwraca metryki tytułów stron z paginacją",
        hasCommonParams: true,
        specificParams: ["limit", "page"],
      },
      {
        method: "GET",
        path: "/sites/:site/live-user-count",
        name: "Pobierz aktywnych odwiedzających",
        description: "Zwraca liczbę aktywnych sesji w wybranym oknie czasu",
        hasCommonParams: false,
        specificParams: ["minutes"],
      },
    ],
  },
  {
    name: "Zdarzenia",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/events",
        name: "Pobierz zdarzenia",
        description: "Zwraca paginowaną listę zdarzeń z paginacją kursorową",
        hasCommonParams: true,
        specificParams: ["page_size", "since_timestamp", "before_timestamp"],
      },
      {
        method: "GET",
        path: "/sites/:site/events/names",
        name: "Pobierz nazwy zdarzeń",
        description: "Zwraca listę unikalnych nazw zdarzeń własnych wraz z licznikami",
        hasCommonParams: true,
      },
      {
        method: "GET",
        path: "/sites/:site/events/time-series",
        name: "Pobierz zdarzenia w czasie",
        description: "Zwraca szeregi czasowe liczników dla najważniejszych zdarzeń własnych",
        hasCommonParams: true,
        specificParams: ["bucket", "limit"],
      },
      {
        method: "GET",
        path: "/sites/:site/events/count",
        name: "Pobierz liczbę zdarzeń",
        description: "Zwraca szeregi czasowe liczby zdarzeń pogrupowane według typu",
        hasCommonParams: true,
        specificParams: ["bucket"],
      },
      {
        method: "GET",
        path: "/sites/:site/events/properties",
        name: "Pobierz właściwości zdarzeń",
        description: "Zwraca pary klucz-wartość właściwości dla wybranego zdarzenia",
        hasCommonParams: true,
        specificParams: ["event_name"],
        requiredParams: ["event_name"],
      },
      {
        method: "GET",
        path: "/sites/:site/events/outbound",
        name: "Pobierz linki wychodzące",
        description: "Zwraca kliknięcia linków wychodzących wraz z licznikami wystąpień",
        hasCommonParams: true,
      },
    ],
  },
  {
    name: "Błędy",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/errors/names",
        name: "Pobierz nazwy błędów",
        description: "Zwraca unikalne komunikaty błędów wraz z liczbą wystąpień i sesji",
        hasCommonParams: true,
        specificParams: ["page", "limit"],
      },
      {
        method: "GET",
        path: "/sites/:site/errors/events",
        name: "Pobierz zdarzenia błędów",
        description: "Zwraca pojedyncze wystąpienia błędów z kontekstem i stack trace",
        hasCommonParams: true,
        requiredParams: ["errorMessage"],
        specificParams: ["errorMessage", "page", "limit"],
      },
      {
        method: "GET",
        path: "/sites/:site/errors/time-series",
        name: "Pobierz błędy w czasie",
        description: "Zwraca liczbę wystąpień błędów w czasie",
        hasCommonParams: true,
        requiredParams: ["errorMessage"],
        specificParams: ["errorMessage", "bucket"],
      },
    ],
  },
  {
    name: "Boty",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/bots/overview",
        name: "Pobierz przegląd botów",
        description: "Zwraca zagregowane metryki ruchu botów z podziałem według warstwy detekcji",
        hasCommonParams: true,
        specificParams: ["layer"],
      },
      {
        method: "GET",
        path: "/sites/:site/bots/time-series",
        name: "Pobierz boty w czasie",
        description: "Zwraca liczbę żądań botów w czasie",
        hasCommonParams: true,
        specificParams: ["bucket", "layer"],
      },
      {
        method: "GET",
        path: "/sites/:site/bots/by-dimension",
        name: "Pobierz boty według wymiaru",
        description: "Zwraca żądania botów w podziale według wymiaru",
        hasCommonParams: true,
        requiredParams: ["dimension"],
        specificParams: ["dimension", "limit", "page", "layer"],
        parameterMetadata: {
          dimension: {
            label: "Wymiar",
            type: "select",
            options: [
              "browser",
              "browser_version",
              "operating_system",
              "operating_system_version",
              "country",
              "region",
              "city",
              "device_type",
              "referrer",
              "hostname",
              "pathname",
              "dimensions",
              "asn_org",
              "bot_category",
              "matched_ua_pattern",
            ],
          },
        },
      },
    ],
  },
  {
    name: "Cele",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/goals",
        name: "Pobierz cele",
        description: "Zwraca paginowaną listę celów z metrykami konwersji",
        hasCommonParams: true,
        specificParams: ["page", "page_size", "sort", "order"],
      },
      {
        method: "GET",
        path: "/sites/:site/goals/time-series",
        name: "Pobierz cele w czasie",
        description: "Zwraca konwersje celów i współczynnik konwersji w czasie",
        hasCommonParams: true,
        requiredParams: ["goal_ids"],
        specificParams: ["goal_ids", "bucket"],
      },
      {
        method: "GET",
        path: "/sites/:site/goals/:goalId/sessions",
        name: "Pobierz sesje celu",
        description: "Zwraca sesje, które zrealizowały wybrany cel",
        hasCommonParams: true,
        pathParams: ["goalId"],
        specificParams: ["page", "limit"],
      },
      {
        method: "POST",
        path: "/sites/:site/goals",
        name: "Utwórz cel",
        description: "Tworzy nowy cel",
        hasCommonParams: false,
        hasRequestBody: true,
        requestBodyExample: {
          name: "Mój cel",
          goalType: "path",
          config: {
            pathPattern: "/checkout/success",
          },
        },
      },
      {
        method: "PUT",
        path: "/sites/:site/goals/:goalId",
        name: "Aktualizuj cel",
        description: "Aktualizuje istniejący cel",
        hasCommonParams: false,
        pathParams: ["goalId"],
        hasRequestBody: true,
        requestBodyExample: {
          name: "Zaktualizowany cel",
          goalType: "event",
          config: {
            eventName: "purchase",
          },
        },
      },
      {
        method: "DELETE",
        path: "/sites/:site/goals/:goalId",
        name: "Usuń cel",
        description: "Usuwa cel",
        hasCommonParams: false,
        pathParams: ["goalId"],
      },
    ],
  },
  {
    name: "Lejki",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/funnels",
        name: "Pobierz lejki",
        description: "Zwraca wszystkie zapisane lejki dla strony",
        hasCommonParams: false,
      },
      {
        method: "POST",
        path: "/sites/:site/funnels/analyze",
        name: "Analizuj lejek",
        description: "Analizuje dane konwersji lejka krok po kroku",
        hasCommonParams: true,
        hasRequestBody: true,
        requestBodyExample: {
          steps: [
            { type: "page", value: "/", name: "Strona główna" },
            { type: "page", value: "/pricing", name: "Cennik" },
            { type: "page", value: "/signup", name: "Rejestracja" },
          ],
        },
      },
      {
        method: "POST",
        path: "/sites/:site/funnels/:stepNumber/sessions",
        name: "Pobierz sesje kroku lejka",
        description: "Zwraca sesje, które dotarły do wybranego kroku lejka albo odpadły na tym kroku",
        hasCommonParams: true,
        pathParams: ["stepNumber"],
        specificParams: ["mode", "page", "limit"],
        requiredParams: ["mode"],
        parameterMetadata: {
          mode: { label: "Tryb", type: "select", options: ["reached", "dropped"] },
        },
        hasRequestBody: true,
        requestBodyExample: {
          steps: [
            { type: "page", value: "/", name: "Strona główna" },
            { type: "page", value: "/pricing", name: "Cennik" },
          ],
        },
      },
      {
        method: "POST",
        path: "/sites/:site/funnels",
        name: "Utwórz lejek",
        description: "Tworzy zapisany lejek",
        hasCommonParams: false,
        hasRequestBody: true,
        requestBodyExample: {
          name: "Lejek konwersji",
          steps: [
            { type: "page", value: "/", name: "Strona główna" },
            { type: "page", value: "/signup", name: "Rejestracja" },
          ],
        },
      },
      {
        method: "DELETE",
        path: "/sites/:site/funnels/:funnelId",
        name: "Usuń lejek",
        description: "Usuwa zapisany lejek",
        hasCommonParams: false,
        pathParams: ["funnelId"],
      },
    ],
  },
  {
    name: "Wydajność",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/performance/overview",
        name: "Pobierz przegląd wydajności",
        description: "Zwraca zagregowane metryki Core Web Vitals",
        hasCommonParams: true,
      },
      {
        method: "GET",
        path: "/sites/:site/performance/time-series",
        name: "Pobierz wydajność w czasie",
        description: "Zwraca metryki wydajności w czasie",
        hasCommonParams: true,
        specificParams: ["bucket"],
      },
      {
        method: "GET",
        path: "/sites/:site/performance/by-dimension",
        name: "Pobierz wydajność według wymiaru",
        description: "Zwraca podział wydajności według wymiaru",
        hasCommonParams: true,
        requiredParams: ["dimension"],
        specificParams: ["dimension", "page", "limit", "sort_by", "sort_order"],
        parameterMetadata: {
          dimension: {
            label: "Wymiar",
            type: "select",
            options: ["pathname", "country", "region", "browser", "operating_system", "device_type"],
          },
          sort_by: {
            label: "Sortuj według",
            type: "select",
            options: [
              "pathname",
              "country",
              "region",
              "browser",
              "operating_system",
              "device_type",
              "event_count",
              "lcp_avg",
              "lcp_p50",
              "lcp_p75",
              "lcp_p90",
              "lcp_p99",
              "cls_avg",
              "cls_p50",
              "cls_p75",
              "cls_p90",
              "cls_p99",
              "inp_avg",
              "inp_p50",
              "inp_p75",
              "inp_p90",
              "inp_p99",
              "fcp_avg",
              "fcp_p50",
              "fcp_p75",
              "fcp_p90",
              "fcp_p99",
              "ttfb_avg",
              "ttfb_p50",
              "ttfb_p75",
              "ttfb_p90",
              "ttfb_p99",
            ],
          },
        },
      },
    ],
  },
  {
    name: "Sesje",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/sessions",
        name: "Pobierz sesje",
        description: "Zwraca paginowaną listę sesji",
        hasCommonParams: true,
        specificParams: ["page", "limit", "user_id", "identified_only", "min_pageviews", "min_events", "min_duration"],
      },
      {
        method: "GET",
        path: "/sites/:site/sessions/:sessionId",
        name: "Pobierz sesję",
        description: "Zwraca szczegółowe informacje o sesji wraz ze zdarzeniami",
        hasCommonParams: false,
        pathParams: ["sessionId"],
        specificParams: ["limit", "offset", "minutes"],
      },
      {
        method: "GET",
        path: "/sites/:site/sessions/locations",
        name: "Pobierz lokalizacje sesji",
        description: "Zwraca zagregowane lokalizacje sesji do wizualizacji na mapie",
        hasCommonParams: true,
      },
    ],
  },
  {
    name: "Odtwarzanie sesji",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/session-replay/list",
        name: "Pobierz odtworzenia sesji",
        description: "Zwraca nagrania odtworzeń sesji z paginacją",
        hasCommonParams: true,
        specificParams: ["limit", "offset", "userId", "minDuration"],
      },
      {
        method: "GET",
        path: "/sites/:site/session-replay/:sessionId",
        name: "Pobierz zdarzenia odtworzenia sesji",
        description: "Zwraca zdarzenia rrweb i metadane dla odtworzenia sesji",
        hasCommonParams: false,
        pathParams: ["sessionId"],
      },
      {
        method: "DELETE",
        path: "/sites/:site/session-replay/:sessionId",
        name: "Usuń odtworzenie sesji",
        description: "Usuwa nagranie odtworzenia sesji",
        hasCommonParams: false,
        pathParams: ["sessionId"],
      },
    ],
  },
  {
    name: "Użytkownicy",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/users",
        name: "Pobierz użytkowników",
        description: "Zwraca paginowaną listę użytkowników",
        hasCommonParams: true,
        specificParams: ["page", "page_size", "sort_by", "sort_order", "identified_only", "search", "search_field"],
        parameterMetadata: {
          sort_by: {
            label: "Sortuj według",
            type: "select",
            options: ["first_seen", "last_seen", "pageviews", "sessions", "events"],
          },
        },
      },
      {
        method: "GET",
        path: "/sites/:site/users/session-count",
        name: "Pobierz liczbę sesji użytkownika",
        description: "Zwraca dzienne liczby sesji dla wybranego użytkownika",
        hasCommonParams: false,
        requiredParams: ["user_id"],
        specificParams: ["user_id", "time_zone"],
      },
      {
        method: "GET",
        path: "/sites/:site/users/:userId",
        name: "Pobierz profil użytkownika",
        description: "Zwraca szczegółowe informacje o profilu użytkownika",
        hasCommonParams: false,
        pathParams: ["userId"],
      },
    ],
  },
  {
    name: "Cechy użytkowników",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/user-traits/keys",
        name: "Pobierz klucze cech użytkowników",
        description: "Zwraca znane klucze cech użytkownika wraz z liczbą użytkowników",
        hasCommonParams: false,
      },
      {
        method: "GET",
        path: "/sites/:site/user-traits/values",
        name: "Pobierz wartości cech użytkownika",
        description: "Zwraca wartości dla klucza cechy użytkownika",
        hasCommonParams: false,
        requiredParams: ["key"],
        specificParams: ["key", "limit", "offset"],
      },
      {
        method: "GET",
        path: "/sites/:site/user-traits/users",
        name: "Pobierz użytkowników według cechy",
        description: "Zwraca użytkowników pasujących do klucza i wartości cechy",
        hasCommonParams: false,
        requiredParams: ["key", "value"],
        specificParams: ["key", "value", "limit", "offset"],
      },
    ],
  },
  {
    name: "Pozostałe",
    endpoints: [
      {
        method: "GET",
        path: "/sites/:site/retention",
        name: "Pobierz retencję",
        description: "Zwraca analizę retencji opartą o kohorty",
        hasCommonParams: false,
        specificParams: ["mode", "range"],
        parameterMetadata: {
          mode: { label: "Tryb", type: "select", options: ["day", "week"] },
        },
      },
      {
        method: "GET",
        path: "/sites/:site/journeys",
        name: "Pobierz podróże",
        description: "Zwraca najczęstsze ścieżki nawigacji po stronach",
        hasCommonParams: true,
        specificParams: ["steps", "limit", "stepFilters"],
      },
      {
        method: "GET",
        path: "/org-event-count/:organizationId",
        name: "Pobierz liczbę zdarzeń organizacji",
        description: "Zwraca dzienne liczby użycia zdarzeń dla organizacji",
        hasCommonParams: false,
        pathParams: ["organizationId"],
        specificParams: ["start_date", "end_date", "time_zone"],
      },
    ],
  },
];

// Flatten all endpoints for easy lookup
export const allEndpoints: EndpointConfig[] = endpointCategories.flatMap(cat => cat.endpoints);

// Parameter metadata for dynamic form generation
export const parameterMetadata: Record<string, ParameterMetadata> = {
  bucket: {
    label: "Przedział",
    type: "select",
    options: ["minute", "five_minutes", "ten_minutes", "fifteen_minutes", "hour", "day", "week", "month", "year"],
  },
  parameter: {
    label: "Parametr",
    type: "select",
    options: [
      "pathname",
      "page_title",
      "querystring",
      "hostname",
      "user_id",
      "event_name",
      "referrer",
      "channel",
      "entry_page",
      "exit_page",
      "country",
      "region",
      "city",
      "device_type",
      "operating_system",
      "operating_system_version",
      "browser",
      "browser_version",
      "language",
      "dimensions",
      "utm_source",
      "utm_medium",
      "utm_campaign",
      "utm_term",
      "utm_content",
      "tag",
      "lat",
      "lon",
      "timezone",
    ],
  },
  dimension: {
    label: "Wymiar",
    type: "select",
    options: ["pathname", "country", "region", "browser", "operating_system", "device_type"],
  },
  layer: {
    label: "Warstwa",
    type: "select",
    options: ["ua_pattern", "header_heuristics", "client_signals", "bot_asn", "rate_anomaly"],
  },
  mode: {
    label: "Tryb",
    type: "select",
    options: ["day", "week", "reached", "dropped"],
  },
  sort: {
    label: "Sortuj według",
    type: "select",
    options: ["goalId", "name", "goalType", "createdAt"],
  },
  sort_by: {
    label: "Sortuj według",
    type: "select",
    options: ["first_seen", "last_seen", "pageviews", "sessions", "events"],
  },
  sort_order: {
    label: "Kierunek sortowania",
    type: "select",
    options: ["asc", "desc"],
  },
  order: {
    label: "Kolejność",
    type: "select",
    options: ["asc", "desc"],
  },
  page: { label: "Strona", type: "number", placeholder: "1" },
  limit: { label: "Limit", type: "number", placeholder: "10" },
  page_size: { label: "Rozmiar strony", type: "number", placeholder: "10" },
  min_pageviews: { label: "Min. odsłon", type: "number", placeholder: "0" },
  min_events: { label: "Min. zdarzeń", type: "number", placeholder: "0" },
  min_duration: { label: "Min. czas trwania (s)", type: "number", placeholder: "0" },
  minDuration: { label: "Min. czas trwania (s)", type: "number", placeholder: "30" },
  minutes: { label: "Minuty", type: "number", placeholder: "5" },
  steps: { label: "Kroki", type: "number", placeholder: "3" },
  stepFilters: { label: "Filtry kroków", type: "text", placeholder: 'JSON, np. {"1":"/pricing"}' },
  range: { label: "Zakres (dni)", type: "number", placeholder: "90" },
  offset: { label: "Przesunięcie", type: "number", placeholder: "0" },
  start_date: { label: "Data początkowa", type: "text", placeholder: "RRRR-MM-DD" },
  end_date: { label: "Data końcowa", type: "text", placeholder: "RRRR-MM-DD" },
  since_timestamp: { label: "Od znacznika czasu", type: "text", placeholder: "ISO 8601, np. 2024-01-31T14:00:00.000Z" },
  before_timestamp: { label: "Przed znacznikiem czasu", type: "text", placeholder: "ISO 8601, np. 2024-01-31T14:00:00.000Z" },
  event_name: { label: "Nazwa zdarzenia", type: "text", placeholder: "np. purchase" },
  errorMessage: { label: "Komunikat błędu", type: "text", placeholder: "Komunikat błędu do filtrowania" },
  user_id: { label: "ID użytkownika", type: "text", placeholder: "ID użytkownika" },
  userId: { label: "ID użytkownika", type: "text", placeholder: "ID użytkownika" },
  key: { label: "Klucz", type: "text", placeholder: "Klucz cechy" },
  value: { label: "Wartość", type: "text", placeholder: "Wartość cechy" },
  search: { label: "Szukaj", type: "text", placeholder: "Szukaj użytkowników" },
  search_field: { label: "Pole wyszukiwania", type: "select", options: ["username", "name", "email", "user_id"] },
  time_zone: { label: "Strefa czasowa", type: "text", placeholder: "Europe/Warsaw" },
  identified_only: { label: "Tylko zidentyfikowani", type: "select", options: ["true", "false"] },
  // Path params
  orgId: { label: "ID organizacji", type: "text", placeholder: "org_abc123" },
  goalId: { label: "ID celu", type: "number", placeholder: "ID celu" },
  goal_ids: { label: "ID celów", type: "text", placeholder: "np. 1,2" },
  funnelId: { label: "ID lejka", type: "number", placeholder: "ID lejka" },
  teamId: { label: "ID zespołu", type: "text", placeholder: "team_abc123" },
  sessionId: { label: "ID sesji", type: "text", placeholder: "ID sesji" },
  stepNumber: { label: "Numer kroku", type: "number", placeholder: "Numer kroku od 1" },
  siteId: { label: "ID strony", type: "number", placeholder: "ID strony" },
  organizationId: { label: "ID organizacji", type: "text", placeholder: "org_abc123" },
  // Sites-specific params
  action: {
    label: "Akcja",
    type: "select",
    options: ["generate_private_link_key", "revoke_private_link_key"],
  },
  // Organizations-specific params
  role: {
    label: "Rola",
    type: "select",
    options: ["admin", "member", "owner"],
  },
};

// Method colors for UI
export const methodColors: Record<HttpMethod, string> = {
  GET: "bg-green-500/20 text-green-600 dark:text-green-400",
  POST: "bg-blue-500/20 text-blue-600 dark:text-blue-400",
  PUT: "bg-yellow-500/20 text-yellow-600 dark:text-yellow-400",
  DELETE: "bg-red-500/20 text-red-600 dark:text-red-400",
};
